import random

import pygame

from space_war.game_objects.projectile import Projectile


class Enemy(pygame.sprite.Sprite):
    """Enemy spaceship object.
    Called in Game object in 'state_game' module.
    """
    def __init__(self, data, pos_x: int, pos_y: int, style: int, direction: str = 'right') -> None:
        """
        Parameters:
            data: 'ShareData' object
            pos_x: x position where spaceship will apear
            pos_y: y position where spaceship will apear
            style: enemy spaceship type(1-4)
            direction: initial spaceship move direction(default='right')
        """
        super().__init__()
        self.data = data

        self.style = style
        self.direction = direction  # Initial moving direction
        self.speed = 0.1

        self.__border = 10 if style == 4 else 60  # Left and right border which enemy won't pass
        self.image = self.data.GFX[f'enemy{self.style}']
        self.__mask = pygame.mask.from_surface(self.image)  # Useful for fast pixel perfect collision detection
        self.rect = self.image.get_rect(center=(pos_x + self.__border, pos_y + 40))  # Rectangular coordinates of enemy

        if style == 1:
            self.hp = 1
            self.shoot_ratio = 300
        elif style == 2:
            self.hp = 5
            self.shoot_ratio = 160
        elif style == 3:
            self.hp = 3
            self.shoot_ratio = 300
        elif style == 4:
            self.hp = 300
            self.shoot_ratio = 120
            self.speed = 0.2

        self.__ball_delay = 2000  # Minimum delay beetween boss ball shots
        self.__timer = 0  # Timer used in boss shot sequence
        self.__played_berserker_sound = False

    def update(self, dt: int) -> None:
        """Moving enemy in left or right direction(self.direction) with defined speed(self.speed).
        Called in 'update' method in Game object(game_state module)

        Parameters:
            dt: delta time in ms
        """
        if self.direction == 'left':
            self.rect.x -= round(self.speed * dt)
        elif self.direction == 'right':
            self.rect.x += round(self.speed * dt)

    def projectile_generation(self, dt: int) -> list:
        """Generating enemy projectiles with definied probability(self.shoot_ratio).
        Called in 'update' method in Game object(game_state module)

        Parameters:
            dt: delta time in ms
        """
        projectiles = []  # Projectiles generated by enemy
        if self.style < 4:
            if random.randint(1, self.shoot_ratio) == 1:
                self.data.SFX['laser-enemy'].play()
                projectile = Projectile(self.data, self.rect.centerx, self.rect.centery, f'enemy{self.style}')
                projectiles.append(projectile)
                if self.style == 3:
                    projectile = Projectile(self.data, self.rect.centerx - 24, self.rect.centery + 20, 'enemy3')
                    projectiles.append(projectile)
                    projectile = Projectile(self.data, self.rect.centerx + 24, self.rect.centery + 20, 'enemy3')
                    projectiles.append(projectile)
        elif self.style == 4:  # Boss enemy
            if self.hp > 200:
                if random.randint(1, self.shoot_ratio) == 1 and pygame.time.get_ticks()-self.__timer > self.__ball_delay:
                    self.data.SFX['ball'].play()
                    projectile = Projectile(self.data, self.rect.centerx, self.rect.centery + 100, 'enemy-ball')
                    projectiles.append(projectile)
                    self.__timer = pygame.time.get_ticks()
                elif random.randint(1, self.shoot_ratio) == 1:
                    self.data.SFX['laser-enemy'].play()
                    projectile = Projectile(self.data, self.rect.centerx - 155, self.rect.centery, 'enemy-smallball')
                    projectiles.append(projectile)
                    projectile = Projectile(self.data, self.rect.centerx + 155, self.rect.centery, 'enemy-smallball')
                    projectiles.append(projectile)
                elif random.randint(1, self.shoot_ratio) == 1:
                    self.data.SFX['laser-enemy'].play()
                    projectile = Projectile(self.data, self.rect.centerx - 115, self.rect.centery + 145, 'enemy4')
                    projectiles.append(projectile)
                    projectile = Projectile(self.data, self.rect.centerx + 115, self.rect.centery + 145, 'enemy4')
                    projectiles.append(projectile)
                elif random.randint(1, self.shoot_ratio) == 1:
                    self.data.SFX['laser-enemy'].play()
                    projectile = Projectile(self.data, self.rect.centerx - 120, self.rect.centery - 105, 'enemy4')
                    projectiles.append(projectile)
                    projectile = Projectile(self.data, self.rect.centerx + 120, self.rect.centery - 105, 'enemy4')
                    projectiles.append(projectile)
            else:
                projectiles = self.__boss_berserker(dt)

        return projectiles

    def __boss_berserker(self, dt: int) -> list:
        """Boss sequence in berserker mode.
        Starts when enemy hp is low enough.

        Parameters:
            dt: delta time in ms
        """

        if not self.__played_berserker_sound:
            self.data.SFX['enemy-berserker'].play()
            self.data.SFX['enemy-berserker2'].play()
            self.__timer = 0  # Timer used for sequences parts
            self.timer2 = 0  # Timer used for delay between shoots in sequences
            self.__played_berserker_sound = True

        self.__timer += dt
        self.timer2 += dt
        self.speed = 0.5
        projectiles = []

        if 2000 < self.__timer < 8000:
            if self.timer2 > 600:
                self.timer2 = 0
                self.data.SFX['ball'].play()
                projectile = Projectile(self.data, self.rect.centerx, self.rect.centery + 100, 'enemy-ball')
                projectiles.append(projectile)
        elif 8500 < self.__timer < 15000:
            if self.timer2 > 400:
                self.timer2 = 0
                self.data.SFX['laser-enemy'].play()
                projectile = Projectile(self.data, self.rect.centerx - 155, self.rect.centery, 'enemy-smallball')
                projectiles.append(projectile)
                projectile = Projectile(self.data, self.rect.centerx + 155, self.rect.centery, 'enemy-smallball')
                projectiles.append(projectile)
        elif 16000 < self.__timer < 30000:
            if self.timer2 < 1000:
                self.data.SFX['laser-enemy'].play()
                projectile = Projectile(self.data, self.rect.centerx - 120, self.rect.centery - 105, 'enemy4')
                projectiles.append(projectile)
                projectile = Projectile(self.data, self.rect.centerx + 120, self.rect.centery - 105, 'enemy4')
                projectiles.append(projectile)
            elif self.timer2 > 2000:
                self.timer2 = 0
        elif self.__timer > 30000:
            self.__timer = 0

        return projectiles
